# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node and different browsers
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 12.x
          - node-version: 14.x
          - node-version: 16.x
          - node-version: 14.x
            browser: "ChromeHeadless"
          - node-version: 14.x
            browser: "FirefoxHeadless"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - if: ${{ matrix.browser }}
      run: npm run test-browsers -- --browsers=${{ matrix.browser }}
    - if: ${{ !matrix.browser }}
      run: npm run test-node
