# This workflow will run tests using node and then publish a package to NPM
# when a release is created
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 14.x
          - node-version: 16.x
          - node-version: 18.x
          - node-version: 20.x
          - node-version: 16.x
            browser: "ChromeHeadless"
          - node-version: 16.x
            browser: "FirefoxHeadless"

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - if: ${{ matrix.browser }}
      run: npm run test-browsers -- --browsers=${{ matrix.browser }}
    - if: ${{ !matrix.browser }}
      run: npm run test-node

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
